all:
	cd ..; make
aarray:
	cd ..; make aarray
aarray_test:
	cd ..; make aarray_test
varray:
	cd ..; make varray
varray_test:
	cd ..; make varray_test
sarray:
	cd ..; make sarray
sarray_test:
	cd ..; make sarray_test
clean:
	cd ..; make clean
